### ISSUE TITLE
Change pacstrap for LTS kernel

### ISSUE THREAD

**Issue by Nandicre** [CarlDuff/aif-dev#1]
Hi. You can easily replace the latest kernel by the lts in the base group with this command:

`pacstrap /mnt $(pacman -Sqg base | sed 's/^linux$/&-lts/')`

Thanks for your script :)

**Comment by CarlDuff** [comment]
Hey - thanks for this! Will try it out and add to the development version. Apologies for not getting back sooner.

**Comment by CarlDuff** [comment]
Done! Nice simple coding!
